/**
 * functions/src/slipTypes.ts
 *
 * Shared Firestore document shapes for the full slip prediction system.
 *
 * Collections
 * ───────────
 *  slips/{slipId}                   — one slip per user per gameweek per mode
 *  h2hLeagues/{leagueId}            — head-to-head mini-leagues
 *  userStats/{uid}                  — XP, streak, badges, record
 *  matchResultCache/{matchId}       — match result + scorer data written before scoring
 */

// ─── Pick types ───────────────────────────────────────────────────────────────

export type PickType =
  | 'result'        // home / draw / away
  | 'overUnder'     // value: 'over_2.5' | 'under_3.5'  etc.
  | 'btts'          // value: 'yes' | 'no'
  | 'correctScore'  // value: '2-1' | '0-0' etc.
  | 'firstScorer'   // value: '{playerId}'
  | 'anytimeScorer' // value: '{playerId}'
  | 'htft';         // value: 'home_home' | 'draw_away' etc.

export interface SlipPick {
  matchId:         string;
  type:            PickType;
  /** Encoded value — see PickType doc above */
  value:           string;
  /** Max points available for this market (informational, set by client) */
  pointsAvailable: number;
  // ── Filled in when this pick is scored ──────────────────────────────────────
  pointsEarned?:   number;
  correct?:        boolean;
  /** The actual resolved value for this market */
  actualValue?:    string;
}

// ─── Slip (/slips/{slipId}) ───────────────────────────────────────────────────

export type SlipMode   = 'solo' | 'h2h';
export type SlipStatus = 'pending' | 'partial' | 'scored';

export interface Slip {
  id:                string;
  userId:            string;
  gameweek:          string;   // e.g. "39_GW12_2024"
  competition:       string;   // e.g. "39" (API-Football league id as string)
  mode:              SlipMode;
  /** H2H only — the opponent's uid */
  challengedUserId?: string;
  /** H2H only — the h2hLeague doc id */
  leagueId?:         string;
  /** True once the first match in the slip has kicked off — no further edits allowed */
  locked:            boolean;
  picks:             SlipPick[];
  /** Raw sum before parlay multiplier */
  rawPoints:         number;
  /** 1 (none) | 1.5 (5+ correct) | 2 (all correct) */
  parlayMultiplier:  number;
  totalPoints:       number;
  status:            SlipStatus;
  submittedAt:       FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  updatedAt:         FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
}

// ─── H2H League (/h2hLeagues/{leagueId}) ─────────────────────────────────────

export interface H2HMatchup {
  gw:   string;
  home: string;   // uid
  away: string;   // uid
}

export interface H2HStanding {
  wins:        number;
  losses:      number;
  draws:       number;
  totalPoints: number;
}

export interface H2HLeague {
  id:              string;
  name:            string;
  members:         string[];   // uids
  competition:     string;
  currentGameweek: string;
  /** Round-robin schedule generated by generateH2HSchedule */
  schedule:        H2HMatchup[];
  standings:       Record<string, H2HStanding>;
  createdAt:       FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  updatedAt:       FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
}

// ─── UserStats (/userStats/{uid}) ─────────────────────────────────────────────

export type BadgeId =
  | 'perfectSlip'    // all picks correct in a slip
  | 'correctScore'   // correct score pick correct
  | 'streakX3'       // 3 consecutive gameweeks with ≥1 correct result
  | 'streakX5'       // 5 consecutive
  | 'h2hWinX10';     // 10 H2H wins

export interface UserStats {
  uid:             string;
  totalXP:         number;
  weeklyXP:        number;
  /** Consecutive gameweeks with ≥1 correct result pick */
  streak:          number;
  lastScoredGameweek?: string;
  badges:          BadgeId[];
  predictionRecord: {
    correct: number;
    total:   number;
  };
  h2hRecord: {
    wins:   number;
    losses: number;
    draws:  number;
  };
}

// ─── Match result cache (/matchResultCache/{matchId}) ─────────────────────────

export interface GoalEvent {
  minute:     number;
  scorerId:   string;
  scorerName: string;
  team:       'home' | 'away';
  type:       'normal' | 'penalty' | 'own';
}

export interface MatchResultCache {
  matchId:       string;
  homeGoals:     number;
  awayGoals:     number;
  halftimeHome:  number;
  halftimeAway:  number;
  btts:          boolean;
  goals:         GoalEvent[];
  finished:      boolean;
  cachedAt:      FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
}
